### ISSUE TITLE
Temporarily pause suspender (feature request)

### ISSUE THREAD

**Issue by bowdenjc** [greatsuspender/thegreatsuspender#1154] opened 2020-05-29 18:30 UTC
Using v7.1.6 in Chrome, Win10.

Thought it would be useful/cool to have feature where you can pause the suspender. This would be different from unsuspending all tabs in that it just stops new tabs from being suspended. Idea is that you would use this when opening a bunch of new tabs that you are going to use for a period of time and would like open, but don't want to have to go set them all to never unsuspend or change timeout time for all tabs. You would press some sort of pause button in the extension menu, and while this is on, no new tabs would be suspended. That's all.

**Comment by ossilator** [comment] 2020-05-29 19:47
wouldn't you just want #818 instead?

**Comment by nathgit** [comment] 2020-05-30 01:45
I can understand what they mean. They want to leave the other tabs suspended, but don't want to suspend new tabs.

**Comment by AmineI** [comment] 2020-05-30 10:11
![image](https://user-images.githubusercontent.com/15179425/83325708-a1a0e580-a26e-11ea-8ef0-53dbcec187ce.png)
I'm new to the extension, (just installed the latest master) but I have this which seems to be what you want ?

**Comment by jbowden200** [comment] 2020-05-31 06:37
Not exactly #818 (seems like don’t suspend any tabs in window). I want to leave suspended tabs as they are, but make sure tabs that aren’t currently suspended stay unsuspended for a period of time while I use them. And then afterward would resume normal behavior.

**Comment by ossilator** [comment] 2020-05-31 10:36
there is no contradiction at all here. #818 refers to the action of suspending, not the state of being suspended.

**Comment by deanoemcke** [comment] 2020-05-31 10:55
Thanks for the feedback. This is a duplicate of: https://github.com/greatsuspender/thegreatsuspender/issues/256
The workaround for this is to change your suspend time in options to 'never'.

**Closed by deanoemcke** 2020-05-31 10:55 UTC
