### ISSUE TITLE
History on iOS

### ISSUE THREAD

**Issue by PauloFranc** [greatsuspender/thegreatsuspender#1148] opened 2020-05-29 09:44 UTC
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6
 * Browser name & version: Chrome
 * Operating system & version: Windows and iOS

First, thanks for the extension, it's very useful.
My question is this: I have several tabs suspended in a Chrome session on my PC and, it I use Chrome for iOS, it permits opening tabs that were open under my Chrome account on the PC.
The problem is that the link for the tab is the "suspended" link.

Is there a way to "unsuspend" a tab it if's being accessed by Chrome for iOS?

Thanks

**Comment by deanoemcke** [comment] 2020-05-31 10:45
Unfortunately this is not a trivial issue to solve. I have tried before without success. To at least make this possible, I've included the full url within the suspended one, so if you edit the url in the address bar on your phone, you should be able to reduce it down to the real url.
I'll close this as a duplicate of: https://github.com/greatsuspender/thegreatsuspender/issues/46

**Closed by deanoemcke** 2020-05-31 10:45 UTC
