### ISSUE TITLE
v7.1.6 update - removes grouped tabs from Chrome

### ISSUE THREAD

**Issue by davedaurelle** [greatsuspender/thegreatsuspender#1149] opened 2020-05-29 10:06 UTC
Great Suspender v7.1.6
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
MS Windows Version 1909 (OS Build 18363.836)

When I updated to the current (v7.1.6) version of the Great Suspender, my grouped tabs function in chrome was deleted.  I had to re-create the groups and re-add all the tabs back into them.

**Comment by Poopooracoocoo** [comment] 2020-05-31 03:00
#1160 
>The chrome.tabs API doesn't expose any of the tab groups functionality yet, so it isn't yet possible for an extension to tell if a tab is in a group or not.

**Comment by deanoemcke** [comment] 2020-05-31 10:46
Will close as a duplicate of: https://github.com/greatsuspender/thegreatsuspender/issues/1160

**Closed by deanoemcke** 2020-05-31 10:46 UTC
