### ISSUE TITLE
Feature Request: Dark Theme Automation

### ISSUE THREAD

**Issue by furiousdom** [greatsuspender/thegreatsuspender#1039] opened 2019-10-03 22:27 UTC
Feature Request: At the theme drop down selection add the option "Based on system" which should set Light or Dark theme based on light or dark theme of the system (Chrome). It should also constantly watch for changes in the system and update the theme appropriately.

**Comment by HoweChen** [comment] 2019-10-08 12:29
This feature would be great!

**Comment by deanoemcke** [comment] 2020-05-31 12:49
Duplicate of: https://github.com/greatsuspender/thegreatsuspender/issues/887

**Closed by deanoemcke** 2020-05-31 12:49 UTC
Labels: feature
