### ISSUE TITLE
Automatically close suspended tabs 

### ISSUE THREAD

**Issue by diallobakary4** [greatsuspender/thegreatsuspender#1053] opened 2019-11-05 06:36 UTC
It will nice to have an option to close suspended tabs after X amount of time. 
I use windows multi-desktop and the number of tabs can easily go wild.

**Comment by deanoemcke** [comment] 2020-05-31 12:50
Duplicate of: https://github.com/greatsuspender/thegreatsuspender/issues/317

**Closed by deanoemcke** 2020-05-31 12:50 UTC
Labels: feature
